### ISSUE TITLE
 'MoveNetVisualizer' could not be found

### ISSUE THREAD

**Issue by Pankti-Fadia** [natml-hub/Pose-Cam#4]
How to resolve Assets\PoseCam.cs(22,16): error CS0246: The type or namespace name 'MoveNetVisualizer' could not be found (are you missing a using directive or an assembly reference?)  error.

**Comment by olokobayusuf** [comment]
@Pankti-Fadia you'll need to download the [MoveNet predictor](https://hub.natml.ai/@natsuite/movenet) from NatML Hub. Let me know if you face any issues in doing so.
